# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('add_course', 'Add course'),)},
        ),
    ]
