# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20160323_0925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('add_course', 'Add course'),)},
        ),
    ]
