# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20160323_0927'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': (('can_view', 'Can View'), ('can_modify', 'Can Modify'), ('can_create', 'Can Create'))},
        ),
    ]
