# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 15:29
from __future__ import unicode_literals

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='upload',
            field=models.FileField(upload_to=course.models.upload_location),
        ),
    ]
