# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 10:51
from __future__ import unicode_literals

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20160404_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='upload',
            field=models.FileField(blank=True, upload_to=course.models.upload_location),
        ),
    ]
