# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 08:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0011_auto_20160406_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent', models.ManyToManyField(blank=True, related_name='parents', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': {},
                'permissions': (('add_democourse', 'Add new demo course'), ('edit_democourse', 'Edit demo course'), ('delete_democourse', 'Delete demo course'), ('list_democourse', 'See list of demo courses'), ('view_democourse', 'View demo course profile')),
            },
        ),
    ]
