# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-12 11:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_coursechapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechapter',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2016, 4, 12, 11, 23, 45, 759674, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
