# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_coursechapter_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursechapter',
            name='user',
        ),
    ]
