# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-20 09:21
from __future__ import unicode_literals

import course.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_remove_coursechapter_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='coursechapter',
            old_name='title',
            new_name='subtitle',
        ),
        migrations.RemoveField(
            model_name='course',
            name='upload',
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='upload',
            field=models.FileField(blank=True, upload_to=course.models.upload_location),
        ),
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursechapter',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.Course'),
        ),
    ]
