# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_auto_20160429_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechapter',
            name='choice',
            field=models.IntegerField(choices=[(1, 'HTML'), (2, 'Image'), (3, 'Video'), (4, 'Quiz')], default=1),
        ),
    ]
