# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-02 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_remove_coursechapter_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursechapter',
            name='image',
        ),
    ]
