# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 08:14
from __future__ import unicode_literals

import course.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_remove_coursechapter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechapter',
            name='image',
            field=models.ImageField(blank=True, upload_to=course.models.upload_location),
        ),
    ]
