# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 08:28
from __future__ import unicode_literals

import course.models
from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0034_auto_20160503_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechapter',
            name='image',
            field=models.ImageField(blank=True, upload_to=course.models.upload_location),
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True),
        ),
    ]
